#!/usr/bin/env php
<?php

use PHP_CodeSniffer\Runner;

include_once __DIR__ . '/../vendor/squizlabs/php_codesniffer/autoload.php';

$runner   = new Runner();
$exitCode = $runner->runPHPCBF();
if ($exitCode === 1) {
    $exitCode = 0;
}
exit($exitCode);
